sonata_admin:
    title: 'CASA - Admin'
    title_logo: 'build/images/logo-saclay.95727ae9.svg'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    templates:
        layout: sonata/standard_layout.html.twig

    show_mosaic_button: false
    persist_filters: true

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
