twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        matomo: '%env(MATOMO)%'
        matomo_id: '%env(MATOMO_ID)%'
        matomo_url: '%env(MATOMO_URL)%'
        app_email_address: '%env(APP_EMAIL_ADDRESS)%'
        app_housingRequest_defaultEmail: '%env(HOUSING_REQUEST_DEFAULT_EMAIL)%'
        app_housingRequest_archiveEmail: '%env(HOUSING_REQUEST_ARCHIVE_EMAIL)%'

when@test:
    twig:
        strict_variables: true
