twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        matomo: '%env(MATOMO)%'

when@test:
    twig:
        strict_variables: true
