version: '3'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: psuh-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: symfony
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/psuh-db:/var/lib/postgresql/data:rw

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: symfony
      MINIO_ROOT_PASSWORD: ${S3_STORAGE_PASSWORD:-password}
    ports:
      - '9090:9000'
      - '9091:9001'
    volumes:
      - ./volumes/minio:/data:rw

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  mjml:
    image: adrianrudnik/mjml-server:2.3.0
    restart: on-failure
    ports:
      - '8081:80'

  test-database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test-psuh-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: test-symfony
    ports:
      - '5433:5432'
