version: '3'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: psuh-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: symfony
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/psuh-db:/var/lib/postgresql/data:rw
