version: '3'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: php
    restart: unless-stopped
    user: '${UID:-0}:${GID:-0}'
    depends_on:
      - database
      - mailhog
      - mjml
      - minio
      - clamav
    env_file: .env.docker.local
    profiles:
      - prod

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    restart: unless-stopped
    depends_on:
      - app
    environment:
      PHP_BACKEND: app
    ports:
      - '8080:80'
    profiles:
      - prod

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: psuh-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: symfony
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/psuh-db:/var/lib/postgresql/data:rw
    profiles:
      - local
      - prod

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: symfony
      MINIO_ROOT_PASSWORD: ${S3_STORAGE_PASSWORD:-password}
    ports:
      - '9090:9000'
      - '9091:9001'
    volumes:
      - ./volumes/minio:/data:rw
    profiles:
      - local
      - prod

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    profiles:
      - local
      - prod

  mjml:
    image: adrianrudnik/mjml-server:2.3.0
    restart: on-failure
    ports:
      - '8081:80'
    profiles:
      - local
      - prod

  clamav:
    restart: on-failure
    image: clamav/clamav
    ports:
      - '3310:3310'
    profiles:
      - local

  test-database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test-psuh-db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: test-symfony
    ports:
      - '5433:5432'
    profiles:
      - test
