site_name: CASA
site_url: https://centralesupelec.github.io/casa/
site_description: Plateforme pour recenser des offres de logement étudiants
site_author: CentraleSupélec

repo_name: CentraleSupelec/casa
repo_url: https://github.com/CentraleSupelec/casa

theme:
    name: material
    palette:
        primary: custom
        accent: custom
    logo: assets/logo.svg
    favicon: assets/favicon.ico
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - md_in_html

nav:
    - 'Présentation': 'index.md'
