{{- if .Values.appEnvSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casa.fullname" . }}-env
  labels:
    {{- include "casa.labels" . | nindent 4 }}
type: Opaque
data:
  .env: {{ .Values.appEnvSecret | b64enc }}
{{- end }}
