apiVersion: v1
kind: Service
metadata:
  name: {{ include "casa.fullname" . }}-mjml
  labels:
    {{- include "casa.commonLabels" . | nindent 4 }}
    {{- include "casa.mjmlSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "casa.mjmlSelectorLabels" . | nindent 4 }}
