services:
    admin.lessor:
        class: App\Admin\LessorAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Lessor
              manager_type: orm
              label: Bailleurs
              group: Transverse

    admin.housing_group:
        class: App\Admin\HousingGroupAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingGroup
              manager_type: orm
              label: Groupes de logements
              group: Logement
        calls:
            - ['addChild', ['@admin.housing_group_service', 'housingGroup']]
            - ['addChild', ['@admin.housing', 'housingGroup']]
            - ['addChild', ['@admin.point_of_interest', 'housingGroup']]

    admin.housing:
        class: App\Admin\HousingAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Housing
              manager_type: orm
              label: Logements
              group: Logement
        calls:
            - ['addChild', ['@admin.housing_picture', 'housing']]

    admin.housing_picture:
        class: App\Admin\HousingPictureAdmin
        arguments:
            - '%env(S3_STORAGE_BASE_URL)%/%env(S3_STORAGE_BUCKET_NAME)%'
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingPicture
              manager_type: orm
              label: Photos de logements
              group: Logement

    admin.service:
        class: App\Admin\ServiceAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Service
              manager_type: orm
              label: Services
              group: Référentiels

    admin.housing_group_service:
        class: App\Admin\HousingGroupServiceAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingGroupService
              manager_type: orm
              show_in_dashboard: false

    admin.equipment:
        class: App\Admin\EquipmentAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Equipment
              manager_type: orm
              label: Équipements
              group: Référentiels

    admin.point_of_interest:
        class: App\Admin\PointOfInterestAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\PointOfInterest
              manager_type: orm
              show_in_dashboard: false
