services:
    admin.lessor:
        class: App\Admin\LessorAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Lessor
              manager_type: orm
              label: Bailleurs
              group: Transverse

    admin.housing_group:
        class: App\Admin\HousingGroupAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingGroup
              controller: App\Controller\Admin\GeocodingController
              manager_type: orm
              label: Groupes de logements
              group: Logement
        calls:
            - ['addChild', ['@admin.housing_group_service', 'housingGroup']]
            - ['addChild', ['@admin.housing', 'housingGroup']]
            - ['addChild', ['@admin.point_of_interest', 'housingGroup']]

    admin.housing:
        class: App\Admin\HousingAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Housing
              manager_type: orm
              label: Logements
              group: Logement
        calls:
            - ['addChild', ['@admin.housing_picture', 'housing']]
            - ['addChild', ['@admin.social_scholarship_criterion', 'housing']]
            - ['addChild', ['@admin.school_criterion', 'housing']]

    admin.housing_picture:
        class: App\Admin\HousingPictureAdmin
        arguments:
            - '%env(S3_STORAGE_BASE_URL)%/%env(S3_STORAGE_BUCKET_NAME)%'
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingPicture
              manager_type: orm
              label: Photos de logements
              group: Logement

    admin.service:
        class: App\Admin\ServiceAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Service
              manager_type: orm
              label: Services
              group: Référentiels

    admin.housing_group_service:
        class: App\Admin\HousingGroupServiceAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\HousingGroupService
              manager_type: orm
              show_in_dashboard: false

    admin.equipment:
        class: App\Admin\EquipmentAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Equipment
              manager_type: orm
              label: Équipements
              group: Référentiels

    admin.point_of_interest:
        class: App\Admin\PointOfInterestAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\PointOfInterest
              manager_type: orm
              show_in_dashboard: false

    admin.school:
        class: App\Admin\SchoolAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\School
              controller: App\Controller\Admin\GeocodingController
              manager_type: orm
              label: Établissement
              group: Établissements
        calls:
            - [
                  'addChild',
                  ['@admin.school_emergency_qualification_question', 'school'],
              ]

    admin.school_emergency_qualification_question:
        class: App\Admin\SchoolEmergencyQualificationQuestionAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\SchoolEmergencyQualificationQuestion
              manager_type: orm
              show_in_dashboard: false

    admin.student:
        class: App\Admin\StudentAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Student
              controller: ~
              manager_type: orm
              group: Utilisateurs
              label: Étudiants

    admin.administrator:
        class: App\Admin\AdministratorAdmin
        arguments:
            - '@App\Service\UserService'
            - ~
            - App\Entity\Administrator
            - ~
        tags:
            - name: sonata.admin
              model_class: App\Entity\Administrator
              controller: ~
              manager_type: orm
              group: Utilisateurs
              label: Administrateurs

    admin.social_scholarship_criterion:
        class: App\Admin\SocialScholarshipCriterionAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\SocialScholarshipCriterion
              manager_type: orm
              show_in_dashboard: false

    admin.school_criterion:
        class: App\Admin\SchoolCriterionAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\SchoolCriterion
              manager_type: orm
              show_in_dashboard: false

    admin.parent_school:
        class: App\Admin\ParentSchoolAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\ParentSchool
              manager_type: orm
              label: Établissement Principal
              group: Établissements
