home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /fr

controllers:
    resource: ../src/Controller/*
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr'
    exclude: ../src/Controller/Admin/

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
