home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /fr

# Temporary Prod Catch All except Admin
# Uncomment this part to activate the "Temporary page"
# catch_non_admin:
#     path: /{_locale}/{foo}
#     requirements:
#         foo: '.*'
#         _locale: 'en|fr'
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
#     defaults:
#         path: /soon

controllers:
    resource: ../src/Controller/*
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr'
    exclude: ../src/Controller/(.*)Admin/

# No Prefix for this route.
# soon_controller:
#     resource: ../src/Controller/Temporary/
#     type: annotation

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation

lessor_admin_controllers:
    resource: ../src/Controller/LessorAdmin/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
