# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - resource: admin.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Make classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Listener\LastLoginListener:
        tags:
            - name: kernel.event_listener
              event: security.interactive_login

    App\Service\ImageUrlService:
        arguments:
            - '%env(S3_STORAGE_BASE_URL)%/%env(S3_STORAGE_BUCKET_NAME)%'

    App\Service\MapService:
        arguments:
            $apiKey: '%env(GEOCODING_API_ID)%'
            $serviceUrl: '%env(GEOCODING_API_URL)%'

    Symfony\Component\Uid\Factory\UuidFactory:
        arguments:
            - 'Symfony\Component\Uid\UuidV4'

    s3_object_storage:
        class: Aws\S3\S3Client
        arguments:
            - version: '2006-03-01'
              region: '%env(S3_STORAGE_REGION)%'
              use_path_style_endpoint: true
              credentials:
                  key: '%env(S3_STORAGE_ACCESS_KEY)%'
                  secret: '%env(S3_STORAGE_SECRET_KEY)%'
              endpoint: '%env(S3_STORAGE_ENDPOINT_URL)%'

    mjml_renderer:
        class: App\Service\MjmlRenderer
        arguments:
            $mjmlBaseUri: '%env(MJML_PROTOCOL)%://%env(MJML_HOST)%:%env(MJML_PORT)%'
